version: "3.7"

services:
#   front:
#     container_name: front
#     build:
#       context: ./front
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     working_dir: /src
#     volumes:
#       - ./front:/src
#     env_file:
#       - ./front/.env
#     tty: true
#     stdin_open: true

  api:
    build:
      context: .
      dockerfile: ./api/build/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    tty: true

  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres/init.d:/docker-entrypoint-initdb.d
      - ./db/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root       # DB USER
      POSTGRES_PASSWORD: root   # DB Password
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always

  pgadmin4:
    image: dpage/pgadmin4:4.2
    container_name: pgadmin4
    ports:
      - "8000:80"
    volumes:
      - ./db/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root     # pgAdmin Address
      PGADMIN_DEFAULT_PASSWORD: root  # pgAdmin Password
    links:
      - db
    restart: always